### ISSUE TITLE
在将yolov5s-seg.onnx编译成axmodel模型时遇到错误

### ISSUE THREAD

**Issue by ABC1234-gitup** [AXERA-TECH/ax-samples#114]
错误是：
Traceback (most recent call last):
  File "<frozen yamain.common.error>", line 53, in guard_context
  File "<frozen yamain.command.build>", line 951, in compile_ptq_model
  File "<frozen yamain.command.build>", line 1069, in compile_npu_subgraph
  File "<frozen yasched.test_onepass>", line 2400, in test_onepass_ir
  File "<frozen yasched.test_onepass>", line 2537, in graph2models
  File "<frozen yasched.test_onepass>", line 495, in graph_sched
  File "<frozen yasched.test_onepass>", line 441, in graph_ddr
ValueError: list.remove(x): x not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "</opt/pulsar2/yamain/main.py>", line 4, in <module>
  File "<frozen yamain.main>", line 282, in <module>
  File "<frozen yamain.main>", line 210, in pulsar2
  File "<frozen yamain.main>", line 143, in wrapper
  File "<frozen yamain.common.error>", line 17, in wrapper
  File "<frozen yamain.command.build>", line 191, in build_error
  File "<frozen yamain.common.error>", line 11, in wrapper
  File "<frozen yamain.command.build>", line 473, in build
  File "<frozen yamain.command.build>", line 991, in compile_ptq_model
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "<frozen yamain.common.error>", line 55, in guard_context
  File "<frozen yamain.common.error>", line 67, in error_func
yamain.common.error.CodeException: (<ErrorCode.NPUBackendError: 8>, ValueError('list.remove(x): x not in list'))
请问这个错误要怎么解决？

**Comment by ZHEQIUSHUI** [comment]
进群问哦
